version: '3.8'

services:
  orsservice:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./app:/app/app
      - ./api:/app/api

    env_file:
      - .env
    container_name: ors_service_container
    ports:
      - "8007:80"
    networks:
      - default
    command: uvicorn app.main:app --host 0.0.0.0 --port 80

networks:
  default:
    external: true
    name: shared-net  
    