version: '3.8'

services:
  orsservice:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./app:/app/app

    env_file:
      - .env
    container_name: ors_service_container
    ports:
      - "8007:80"
    networks:
      - default

networks:
  default:
    external: true
    name: shared-net  
    